### PR TITLE
Code improvement

### PR DESCRIPTION
**Pull request by Rahulbaran**
- Hey Vedanshi, I made the changes required to make your code clean and improve site performance(#5)

> **Note**
> I made following changes:-
> 1.  improved structure of html code
> 2.  compressed some images & converted them in `.webp` format.
> 3.  wrote cleaner code for styling(**CSS**) and used **Nunito** font by [google fonts](https://fonts.google.com/)
>  4.  added a `.gitignore` file

- I have included the screen shots of the site both in **light and dark modes**.
- Let me know, if you need any help regarding the code.

### Light Mode
light-ss

### Dark Mode
dark-ss

### CODE REVIEW

**Comment by vedanshi555** [comment]
hey, regarding the changes I have some questions and some changes that i don't prefer...
-  please keep the original photo in both light mode and dark mode.
- how do i change the light mode and dark mode in website...like is there any button or something else for that?
- what does `.gitignore`  file do, or what is it for?

other than this, thank you for converting those pics in .webp format and the code looks more decent now.
I did like the new fonts:))

**Comment by Rahulbaran** [comment]
- You will have to create a button for switching between **light & dark**. I have just added a **media query** `prefers-color-scheme` to change the colors based on system preferences([read here](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme))

- There are certain folders/files which we don't want to push to **github**( like **node_modules, .vscode, .DS_Store** etc) and by using `.gitignore`, we let the **git** to know  about ignoring them.

- Let me remove the **filter**, I applied on **avatar**.

**Comment by Rahulbaran** [comment]
I removed the filter, now you checkout

**Review by vedanshi555 — APPROVED** [review]

**Comment by Rahulbaran** [comment]
Thank you🤗
Have a happy Sunday

**Comment by vedanshi555** [comment]
> Thank you🤗 Have a happy Sunday

you too:)

**Pull request merged**
